USE [master]
GO

/****** Object:  Database [CafeManagement]    Script Date: 8/5/2020 9:40:53 PM ******/
CREATE DATABASE [CafeManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CafeManagement', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CafeManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CafeManagement_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CafeManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CafeManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CafeManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CafeManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CafeManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CafeManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CafeManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [CafeManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CafeManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CafeManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CafeManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CafeManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CafeManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CafeManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CafeManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CafeManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CafeManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CafeManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CafeManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CafeManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CafeManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CafeManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CafeManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CafeManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CafeManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [CafeManagement] SET  MULTI_USER 
GO

ALTER DATABASE [CafeManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CafeManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CafeManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CafeManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CafeManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CafeManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CafeManagement] SET  READ_WRITE 
GO

